### ISSUE TITLE
Invalid isConnected function

### ISSUE THREAD

**Issue by tnicolas42** [RobTillaart/AD5245#8]
https://github.com/RobTillaart/AD5245/blob/ce6560581e2854851b8ccfbda1442f4f3b86846f/AD5245.cpp#L29

This line will always return false.
May be you want to do
```
 if ((_address != 0x2C) && (_address != 0x2D)) return false; 
```

**Comment by RobTillaart** [comment]
@tnicolas42 
you're 100% right, I will create a PR (0.4.0)  asap.
I might include some minor edits too.

If there are other things need to fix or you would like to have, do not hesitate to share,
Thanks for finding this bug.

**Comment by RobTillaart** [comment]
develop branch, PR created, build is running.
